## BASH SETUP ##
function nonzero_return() {
        RETVAL=$?
        [ $RETVAL -ne 0 ] && echo "$RETVAL "
}

export PS1="\[\e[33m\]\u\[\e[m\]\[\e[33m\]@\[\e[m\]\[\e[33m\]\h\[\e[m\] \w\[\e[36m\]\n\`nonzero_return\`$\[\e[m\]  "
## END BASH SETUP ##
